AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Uploader
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: Bucket
      PolicyDocument:
        Id: BucketPolicy
        Statement:
        - Action: ['s3:PutObject']
          Effect: Allow
          Principal:
            AWS:
              Fn::GetAtt: [User, Arn]
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:s3:::'
              - Ref: Bucket
              - /*
        - Action: ['s3:GetObject']
          Effect: Allow
          Principal: '*'
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:s3:::'
              - Ref: Bucket
              - /*
  HostKeys:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName:
        Ref: User
  User:
    Type: AWS::IAM::User
Outputs:
  AwsId:
    Value:
      Ref: HostKeys
  AwsSecret:
    Value:
      Fn::GetAtt: [HostKeys, SecretAccessKey]
  Bucket:
    Value:
      Ref: Bucket
