AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Uploader DEV
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: Bucket
      PolicyDocument:
        Id: BucketPolicy
        Statement:
        - Action: ['s3:GetObject']
          Effect: Allow
          Principal: '*'
          Resource:
            Fn::Join: ['', ['arn:aws:s3:::', {Ref: Bucket}, '/*' ]]
Outputs:
  Bucket:
    Value:
      Ref: Bucket
